### ISSUE TITLE
Upscale not working

### ISSUE THREAD

**Issue by phail216** [SeargeDP/SeargeSDXL#128]
Hi,
as the title says, upscale is not working.
I have no clue why and I don't know how to enable it.
I am searching for Infos since days now, but I cannot find any.
Even if I try the "example-2-high-quality.png", I still get only the normal resolution.
Can you give me any hints on what I'm doing wrong?
Thanks!

![2023-12-29 12_26_43-ComfyUI - Persönlich – Microsoft​ Edge](https://github.com/SeargeDP/SeargeSDXL/assets/25581797/71c70bed-41fa-4fdf-85cc-0a50c4f1d089)

**Comment by Anoromi** [comment]
@phail216 You close this issue as completed. Can you please say if you found a solution?

**Comment by phail216** [comment]
@Anoromi Hi, I did not "found" a solution, it just started working after restarting and reloading multiple times. Although I have no clue why it did not work in the first place.
