### ISSUE TITLE
The "loraLoader" node doesn't support subdirectories.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [SeargeDP/SeargeSDXL#14]
I tried the example workflows, and it kept failing because it couldn't find the lora. I converted the node's "lora_name" to a widget and tried browsing for my SDXL loras (they're all in a subdirectory) and none were shown. All loras not in the subdirectory are shown.

**Comment by SeargeDP** [comment]
Not sure if it's a problem with my workflows or a general ComfyUI issue. Have you tested just putting up a lora loader on an empty node graph to see if it lists all files or just some?

**Comment by Piscabo** [comment]
Same here with your node... other nodes shows the whole list:
![image](https://github.com/SeargeDP/SeargeSDXL/assets/123719842/3a21ce48-fc87-4e96-b0ab-5c5f271bb5e4)
![image](https://github.com/SeargeDP/SeargeSDXL/assets/123719842/04176a9c-66ab-404a-8bc3-1122403e6d66)
I also have no joy in creating anything... input image stays the same throughout...
![image](https://github.com/SeargeDP/SeargeSDXL/assets/123719842/cb5b086f-0711-4b82-8def-7de4665d08bb)

**Comment by SeargeDP** [comment]
I'll look into it.

And with the img2img workflow, you have to change the input image. Maybe you are looking for the text2img workflow? That would be called the reborn workflow, check the json files.

**Comment by Grimsanta** [comment]
I as well have the exact same issue in the same manner as they do. My Lora's wont load in the "LoRA Model" but if I add a "Load LoRA" node it will bring up all that I have and let me use them.

**Comment by SeargeDP** [comment]
Is anyone having this problem here using an older version of ComfyUI or are you all on the latest version? I heard that there was some problem with LoRA loading at some point recently but it got apparently already fixed.

**Comment by GalaxyTimeMachine** [comment]
I update daily. Other nodes are able to read Lora subdirectories, just not your one.

**Comment by GalaxyTimeMachine** [comment]
I am mapping to remote directories, so I don't know if that has anything to do with it.

**Comment by Grimsanta** [comment]
I've tried other workflows that have LoRA support and mine are loading in theirs. I tried with the default ComfyUI that you get after first install and setup the Load LoRA and was able to select and use all my SDXL 1.0 LoRA without issue. I do have all my checkpoints, LoRA's, etc in my A1111 directory and use the `extra_model_paths.yaml` and it works as stated in everything but this particular workflow.

**Comment by SeargeDP** [comment]
Ok, awesome feedback. I'll look into it and hopefully solve it for the next version of the workflows.

**Comment by Grimsanta** [comment]
Ive found something via the comments on CivitAI which seems to have solved it.

1. When going down to the Load LoRA node and right-click on convert lora_name to widget
![Screenshot 2023-08-02 061442](https://github.com/SeargeDP/SeargeSDXL/assets/81027827/db5afe20-5993-4989-b90d-af180b35f160)
2. Then turn it back into an input
![Screenshot 2023-08-02 061626](https://github.com/SeargeDP/SeargeSDXL/assets/81027827/2021677a-ac39-461e-9758-35dd3c489ed1)
rt
3. Reconnect the wires so that everything is back to the way it was to staart with
4. Profit, you can now change and detect all LoRA's
![Screenshot 2023-08-02 061801](https://github.com/SeargeDP/SeargeSDXL/assets/81027827/a18f02b6-5ee0-4321-adce-a77ae09f8396)

**Comment by danielpdykes** [comment]
Can confirm that @Grimsanta 's step by step fixes it for me and the fields then accurately populate.

**Comment by SeargeDP** [comment]
Ok, awesome feedback. I'll make a fix for the next update of the workflow so you don't have to reconnect any wires to update the selector

**Comment by GoldmanOz** [comment]
I'm also having Lora problems, I can see all Loras and select the correct one in the loader but am then getting errors because Comfy is trying to read ALL of the Loras I have it would seem...Terminal reads ' Return type mismatch between linked nodes: lora_name,' then lists all of my Loras..

**Comment by SeargeDP** [comment]
Is this still a problem in version 3.1 of my workflow?

**Comment by GalaxyTimeMachine** [comment]
Not for me.

**Comment by SeargeDP** [comment]
Seems to be fixed now
