### ISSUE TITLE
It ignores my prompt, generates random images

### ISSUE THREAD

**Issue by 2blackbar** [SeargeDP/SeargeSDXL#23]
What the hell i feel like total noob, i did not changed anything at all just input my own prompt into main prompt window, is there a video on how to use it for various txt2img img2img inpaint modes cause theyre really a must , this node setup is damn scary and big
No clue how to go to img2img 
No clue how to go to inpaint
No clue why theres not a single info about it  next to install instructions , i mean explain it like were 5 years old, this might be comfortable for you but not for newcomers, i do know how nodes work but i have no clue what to do anways, and on top of that it ignores my prompts 

Ok looks like most recent json file is borked
I got older one and it works , still i would like to know how to use img2img or inpaint , that info should be on mainpage

**Comment by SeargeDP** [comment]
This is not a bug. There is going to be more documentation in the future, for now it's all provided as-is. And if you want simpler prompting, switch the prompting style to "simple" and you only have to care about the main prompt and negative prompt.
