### ISSUE TITLE
batch_size does not affect inpainting or img2img modes (see fix attached)

### ISSUE THREAD

**Issue by naql** [SeargeDP/SeargeSDXL#25]
I noted this with 3.0 and spent some time fixing it last night.  Should have reported it here, but did so on reddit.
The fix that was working for me is attached and was working, prior to downloading 3.1 and running into another issue.

The change is an import of torch, and then to modify SeargeLatentMuxer3 to pass in the batch_size and then, for inpaint and img2img modes only, to use torch.repeat to fill out the latents to the batch size.

[searge_sdxl_sampler_node.zip](https://github.com/SeargeDP/SeargeSDXL/files/12268089/searge_sdxl_sampler_node.zip)

**Comment by naql** [comment]
was not clear to me whether I should have used torch.expand versus torch.repeat (I am a programmer, but a complete Python/Torch novice).  expand is supposed to be more memory efficient, not sure if it repeats the data as needed, but I'll test it out.

**Comment by SeargeDP** [comment]
Could you fork the project and make a pull request? I can't really see the changes when it's just a zip file with the changed file in it.

**Comment by naql** [comment]
As you have shown, this can be accomplished by adding two "Repeat Latent Batch" nodes on the inpainting and img2img routes immediately before the SeargeLatentMuxer3 node.

**Comment by SeargeDP** [comment]
Ok. Thanks for the PR, even if it didn't get merged. I was actually not aware of that node myself, so we both learned something. I'll close this now and put it on my todo list to add batch size support to those modes in the future.
