### ISSUE TITLE
As of 3.1, error in loading models, lora, vae

### ISSUE THREAD

**Issue by naql** [SeargeDP/SeargeSDXL#26]
#Prompt outputs failed validation
CheckpointLoaderSimple:
- Return type mismatch between linked nodes: ckpt_name, CHECKPOINT_NAME != ['Deliberate-inpainting.safetensors', 'analogMadness_v50.safetensors', 'clarity_-inpainting.safetensors', 'clarity_2.safetensors', 'cyberrealistic_v31-inpainting.safetensors', 'cyberrealistic_v31.safetensors', 'deliberate_v2.safetensors', 'dreamlikePhotoreal20_dreamlikePhotoreal20.safetensors', 'dreamshaperXL10_alpha2Xl10.safetensors', 'dreamshaper_4-inpainting.safetensors', 'dreamshaper_4BakedVae.safetensors', 'dreamshaper_7.safetensors', 'f222.ckpt', 'moreRealistic_v10.ckpt', 'protogenX34Photorealism_1.safetensors', 'protogenX53Photorealism_10.safetensors', 'realisticVisionV13_v13.safetensors', 'rundiffusionXL_beta.safetensors', 'sd_xl_base_1.0.safetensors', 'sd_xl_refiner_1.0.safetensors', 'talmendoxlSDXL_v11Beta.safetensors', 'v1-5-pruned-emaonly.ckpt', 'v2-1_768-ema-pruned.safetensors']
VAELoader:
- Return type mismatch between linked nodes: vae_name, VAE_NAME != ['sdxl_vae.safetensors', 'vae-ft-mse-840000-ema-pruned.ckpt', 'vae-ft-mse-840000-ema-pruned.safetensors']
CheckpointLoaderSimple:
- Return type mismatch between linked nodes: ckpt_name, CHECKPOINT_NAME != ['Deliberate-inpainting.safetensors', 'analogMadness_v50.safetensors', 'clarity_-inpainting.safetensors', 'clarity_2.safetensors', 'cyberrealistic_v31-inpainting.safetensors', 'cyberrealistic_v31.safetensors', 'deliberate_v2.safetensors', 'dreamlikePhotoreal20_dreamlikePhotoreal20.safetensors', 'dreamshaperXL10_alpha2Xl10.safetensors', 'dreamshaper_4-inpainting.safetensors', 'dreamshaper_4BakedVae.safetensors', 'dreamshaper_7.safetensors', 'f222.ckpt', 'moreRealistic_v10.ckpt', 'protogenX34Photorealism_1.safetensors', 'protogenX53Photorealism_10.safetensors', 'realisticVisionV13_v13.safetensors', 'rundiffusionXL_beta.safetensors', 'sd_xl_base_1.0.safetensors', 'sd_xl_refiner_1.0.safetensors', 'talmendoxlSDXL_v11Beta.safetensors', 'v1-5-pruned-emaonly.ckpt', 'v2-1_768-ema-pruned.safetensors']
UpscaleModelLoader:
- Return type mismatch between linked nodes: model_name, UPSCALER_NAME != ['4x-UltraSharp.pth', '4x_NMKD-Siax_200k.pth', 'ESRGAN_4x.pth', 'RealESRGAN_x4plus.pth', 'SwinIR_4x.pth']
UpscaleModelLoader:
- Return type mismatch between linked nodes: model_name, UPSCALER_NAME != ['4x-UltraSharp.pth', '4x_NMKD-Siax_200k.pth', 'ESRGAN_4x.pth', 'RealESRGAN_x4plus.pth', 'SwinIR_4x.pth']

**Comment by karl-von-knecht** [comment]
Same here. I made sure to download the required models and put them in the proper places (and other workflows do find them there). It looks like one of the "model names" nodes is simply not working at all.

**Comment by SeargeDP** [comment]
Are you using the latest updated .json file for the latest version of the extension. This sounds like the kind of error I'd expect when trying to use an older workflow version in the updated extension.

**Comment by naql** [comment]
Was getting same error, so, I deleted everything.  Did a fork of your main and downloaded (made my fix for inpaint).  Started up ComfyUI, cleared, reloaded default.  Shut it down and restarted again.  Again reloaded your latest from json.  Now, when I queue, I am only getting this one:

```
SeargeInput4:
- Value not in list: lora_model: 'sd_xl_offset_example-lora_1.0.safetensors' not in ['LowRa.safetensors', 'Race - SuccubusV2.safetensors', 'SDXL_finenude_v0_2a.safetensors', 'SDXL_frazetta_lora.safetensors', 'SDXL_neg4all_xl_bdsqlsz_V5.safetensors', 'epi_noiseoffset2.safetensors', 'more_details.safetensors']
```

**Comment by naql** [comment]
Ok, so I deleted my existing "Model Names" SeargeInput4 node, re-added another from the context menu, hooked it up and it works.  So, it does seem to be some sort of issue of caching up the old version somewhere.

**Comment by naql** [comment]
Marking it as resolved, since I opened it.
