### ISSUE TITLE
Missing 'SeargePromptCombiner' node from example given.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [SeargeDP/SeargeSDXL#3]
The repo has an example workflow json file that uses a missing node. Could you include the node, or remove it from the workflow if it's not required, please?

![Screenshot 2023-07-15 174242](https://github.com/SeargeDP/SeargeSDXL/assets/52193044/fea45fb7-dd80-4a15-b679-4135497858d2)

**Comment by SeargeDP** [comment]
Did you update this custom extension and restart ComfyUI before loading the workflow? The "missing" node was added just before I added this extended workflow, so if this extension is up to date it should not complain about any missing node types.

**Comment by GalaxyTimeMachine** [comment]
I did update it. The problem is that your example .json has this additional node, but the repo doesn't. I don't think it's even required and doesn't appear in your workflow image, [here](https://github.com/SeargeDP/SeargeSDXL/blob/main/example/Searge-SDXL-img2img.png).
I've edited the workflow to look like the image, and it works that way, but you should remove it from the example json, [here](https://github.com/SeargeDP/SeargeSDXL/blob/main/example/Searge-SDXL-with-upscale.json).

**Comment by SeargeDP** [comment]
How did you install my custom nodes? If you used the `git clone` method you have to use `git pull` in this extensions directory to update to the latest version. If you installed version 1.0.0 from the releases page the new node is indeed not included, but neither is this improved workflow (that was only added to the repository after the new node was added)

**Comment by GalaxyTimeMachine** [comment]
I have 3 different installs and have replaced 2 of them since, so I'm not sure. I only use git or the node manager in the UI, but I noticed that wasn't updating nodes properly. I suspect it was that and have reinstalled the latest portable version, and now it's all working as expected.
Even without that missing node, this workflow has been my favourite for SDXL, so far. Thank you for sharing it!

**Comment by SeargeDP** [comment]
Solved
