### ISSUE TITLE
Generating Error

### ISSUE THREAD

**Issue by bulutharbeli** [SeargeDP/SeargeSDXL#30]
I am getting this error. How to fix that. Thanks
![image](https://github.com/SeargeDP/SeargeSDXL/assets/30212464/01abdbc1-d7a5-40d6-aa4c-c18001799514)

**Comment by SeargeDP** [comment]
Did you download and copy all the [files listed here](https://github.com/SeargeDP/SeargeSDXL#direct-downloads)?

**Comment by bulutharbeli** [comment]
yes i did. it's showing upscaler error but i already installed. 
![image](https://github.com/SeargeDP/SeargeSDXL/assets/30212464/815f6264-5c6e-4c11-b91e-ac95920ff2b9)

**Comment by SeargeDP** [comment]
And you are using the _latest version_ of the custom node extension together with the **latest version of the JSON** workflow file from the `workflow` folder?

**Comment by bulutharbeli** [comment]
Opps ... I figured out where the problem was coming from :( I had to link them together. Sorry for the  trouble.
![image](https://github.com/SeargeDP/SeargeSDXL/assets/30212464/34c7ea51-5597-4491-809c-36aac0cf1296)

**Comment by SeargeDP** [comment]
You can disable upscaling by leaving it disconnected and ignoring the errors. The normal image will still generate, so does the "hires-fixed" version of the image if you enable HRF.

**Comment by bulutharbeli** [comment]
thank you

**Comment by SeargeDP** [comment]
I'll close this as solved.
