### ISSUE TITLE
Hires-fix bug and hires-fix only operation_mode

### ISSUE THREAD

**Issue by Khanation** [SeargeDP/SeargeSDXL#32]
Hi  there,

Great work on the workflow! I enjoy using it immensely, thank you for creating and maintaining it.

I noticed that hires-fix doesn't work when using inpainting - it just outputs the same image. This looks like a bug because it works with text2image and image2image modes.

To work around this issue, I create my image with inpainting first and then I go through an image2image workflow with denoise set to 0 to get my hires-fixed version. However, this workaround will not occur to many users and shouldn't be needed.

Tangentially related to this, currently there is no hires-fix only operation_mode. I sometimes create multiple images with low steps to find something I like and then I copy its seed to work on it further and only then I'd like to go for hires-fix. Adding hires-fix only mode would be helpful for such a workflow.

Thanks.

**Comment by SeargeDP** [comment]
Hires fix was causing issues with inpainting so it is not compatible in older versions of the workflow. It will work in the future.

**Comment by Khanation** [comment]
Understood. Thanks.

**Comment by SeargeDP** [comment]
Try it in v3.4 - I can't remember if it was already fixed there, but it's possible that I already changed it.

**Comment by SeargeDP** [comment]
It was fixed in v3.4
