### ISSUE TITLE
sdxl_vae.safetensors file in workflow is sdxl-vae.safetensors

### ISSUE THREAD

**Issue by ozzeruk** [SeargeDP/SeargeSDXL#34]
Just a small heads-up to anyone struggling with this, I can't remember if I loaded 3.3 or 3.4 but it was one of them. For me having followed the instructions when trying to generate the default image I got an error talking about 'image' and 'sdxl_vae.safetensors'.

It turns out that the main page instructions has you downloading:

https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors

After you have put this in your models/vae folder you need to rename or copy it to:

sdxl-vae.safetensors

The default image of the cat now generates correctly. Issue was a dash needed rather than an underscore. I guess this will be fixed in the next version but just posting in case anyone today is having the issue.

**Comment by SeargeDP** [comment]
This will be changed to the correct default in the next update
