### ISSUE TITLE
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}

### ISSUE THREAD

**Issue by Suzie1** [SeargeDP/SeargeSDXL#36]
I'm getting this message on SDXL Sampler v2

making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
torch.Size([1, 1280]) 4096 4096 0 0 4096 4096
torch.Size([1, 1280]) 4096 4096 0 0 4096 4096
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:13<00:00,  1.22it/s]
torch.Size([1, 1280]) 2048 2048 0 0 6.0
torch.Size([1, 1280]) 2048 2048 0 0 2.5
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.03it/s]
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Prompt executed in 70.55 seconds

**Comment by SeargeDP** [comment]
It's a warning that can be ignored
