### ISSUE TITLE
Loopback wave script

### ISSUE THREAD

**Issue by TomTomGit86** [SeargeDP/SeargeSDXL#39]
Hi great job! Is it possible it integrate the loopback wave script I've been using in auto1111. I've found comfyui better performance for sdxl but lacking some off the ease of use that came with auto1111. Which you've obviously done a lot of work to make this easy to use with your work flow. Thanks for sharing.

**Comment by SeargeDP** [comment]
ComfyUI and A1111 are completely different applications, so this is not easily possible. That being said, I wrote on my todo list to check at some point what that A1111 script does and if it's possible to implement similar functionality in my workflow.

**Comment by TomTomGit86** [comment]
This is what I thought but the principles behind the script could potentially be replicated in comfyui
https://rentry.co/sd-loopback-wave
Here's the link, I'm not to fussed about the ffmpeg part and making a video out of the images I can do that afterwards in using flowframes windows app but if we could output the frames (pics) on this fashion in comfy that would be great

**Comment by SeargeDP** [comment]
I'll close this ticket. It's a feature request and I'm tracking it on my "maybe-todo" list
