### ISSUE TITLE
Toggle for refiner in SeargeSDXL Sampler

### ISSUE THREAD

**Issue by isamarsh** [SeargeDP/SeargeSDXL#4]
Right now the node is hard-coded to always refine. It would be helpful if a toggle could be added to switch the refiner on/off by the user. This way you could do your testing quickly on the base model and then switch on the refiner for the final gen.

**Comment by SeargeDP** [comment]
If you change the base ratio to 1.0 it will only do the base model generation and nothing with the refiner. That's how I sometimes quickly test how it looks with or without the refiner, just switch the ratio between 1.0 and 0.8 (or other values if you want more or less refiner steps)

**Comment by SeargeDP** [comment]
I consider this solved with the comment I wrote 2 days ago.
