### ISSUE TITLE
google colab pro: Failed to validate prompt for output 364

### ISSUE THREAD

**Issue by elemos78** [SeargeDP/SeargeSDXL#41]
I am using google collab pro.

After generating any image, when trying to make a second one, the following message appears. Failed to validate prompt for output 364:
Output will be ignored

After this the notebook disconnects and I have to run the last cell again

**Comment by SeargeDP** [comment]
Those warnings appear when the upscaler is not connected. It's expected to see these warnings and they do not cause any issues. I don't know much about Google Collab, I've never used it and can unfortunately not help with the disconnect issue
