### ISSUE TITLE
New Samplers in ComfyUI Causing issues

### ISSUE THREAD

**Issue by williamcboehmjr** [SeargeDP/SeargeSDXL#44]
They release a few new schedulers and samplers and it's causing an issue:

Prompt outputs failed validation
SeargeSDXLSampler:
- Return type mismatch between linked nodes: sampler_name, SAMPLER_NAME != ['euler', 'euler_ancestral', 'heun', 'dpm_2', 'dpm_2_ancestral', 'lms', 'dpm_fast', 'dpm_adaptive', 'dpmpp_2s_ancestral', 'dpmpp_sde', 'dpmpp_sde_gpu', 'dpmpp_2m', 'dpmpp_2m_sde', 'dpmpp_2m_sde_gpu', 'dpmpp_3m_sde', 'dpmpp_3m_sde_gpu', 'ddim', 'uni_pc', 'uni_pc_bh2']
- Return type mismatch between linked nodes: scheduler, SCHEDULER_NAME != ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform']

![TabTip_RW9lJ46c4k](https://github.com/SeargeDP/SeargeSDXL/assets/112737237/63b849b8-5034-49bc-bdec-8c22b80e207f)

**Comment by SeargeDP** [comment]
Are you using the latest workflow version from the .json file in the workflow folder?

**Comment by williamcboehmjr** [comment]
Ok, you can close this bug. It works.... I must have been using an older version of your workflow. NM.
