### ISSUE TITLE
ControlNet support

### ISSUE THREAD

**Issue by Mapleshade20** [SeargeDP/SeargeSDXL#45]
As presented on [Huggingface ControlNet SDXL](https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0/), it's available now in ComfyUI. Would you like to add this feature?

**Comment by Mapleshade20** [comment]
Besides, this workflow seems to throw out this warning(Failed to validate prompt for output):
```
got prompt
Failed to validate prompt for output 243:
* ImageUpscaleWithModel 66:
  - Required input is missing: image
* ImageUpscaleWithModel 67:
  - Required input is missing: image
Output will be ignored
Failed to validate prompt for output 364:
Output will be ignored
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:07<00:00,  3.40it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.95it/s]
Prompt executed in 20.26 seconds
```

**Comment by SeargeDP** [comment]
You can ignore those warnings, they show up when the upscaler is not connected and it's expected.

About controlnet, it's planned to be added in a future update of the workflow.

**Comment by C0nsumption** [comment]
> You can ignore those warnings, they show up when the upscaler is not connected and it's expected.
> 
> About controlnet, it's planned to be added in a future update of the workflow.

Would you like some help developing on the development?

**Comment by Mapleshade20** [comment]
> > You can ignore those warnings, they show up when the upscaler is not connected and it's expected.
> > About controlnet, it's planned to be added in a future update of the workflow.
> 
> Would you like some help developing on the development?

I really want to, but I’m busy coping with my final school year before entering university… I’ll get much more spare time once after that!
