### ISSUE TITLE
node save_image not work as base from ComfyUI

### ISSUE THREAD

**Issue by pvp-by** [SeargeDP/SeargeSDXL#48]
normal node image_save can use prefix about say as here https://blenderneko.github.io/ComfyUI-docs/Interface/SaveFileFormatting/

can use value from variable %node.widget% , your version of this node has more customization, but lost old functionality.

**Comment by SeargeDP** [comment]
Yes, the custom node I made for saving images has a specific use case that is covered by its implementation. It's not meant to be a general replacement for the ComfyUI node.
