### ISSUE TITLE
Interface not showing 

### ISSUE THREAD

**Issue by jlitz** [SeargeDP/SeargeSDXL#49]
Any possible reason for  this not showing up  on Comfy?  Installed it correctly  and updated   https://i.imgur.com/PpXRMeE.png  Comfy working ok.  but no Searge.  tia  https://i.imgur.com/wQe4R5E.png    never mind   figured it out load workflow

**Comment by cnjsstong** [comment]
same here

**Comment by SeargeDP** [comment]
Did you load the .json file from my `workflow` folder? You can either press the Load button and select the file or just drag the .json file into a browser window that has ComfyUI loaded.

**Comment by SeargeDP** [comment]
closing this due to a lack of replies
