### ISSUE TITLE
[Feature Request] Custom Mask for precise control

### ISSUE THREAD

**Issue by PsiClone99** [SeargeDP/SeargeSDXL#50]
Can we also have **black** and **white** here to upload mask images from another source. (Both Black and white since it is easier to swap channels and experiment in PS and GIMP and bring it here quickly as masks)
![image](https://github.com/SeargeDP/SeargeSDXL/assets/36812989/443cb676-7862-469e-9e0d-8eb0654591f0)

Example - 

![image](https://github.com/SeargeDP/SeargeSDXL/assets/36812989/243f59fa-f37e-4f23-a5d9-149cf64c5677)

**Comment by SeargeDP** [comment]
The Convert Image to Mask node is a ComfyUI standard node that I can't change.

**Comment by PsiClone99** [comment]
Thank you, u understood me correctly, Thanks for considering!

**Comment by SeargeDP** [comment]
In the public test version 3.991 this has been added. Thanks for the suggestion.
