### ISSUE TITLE
[Feature Request] Add Control-Lora workflow

### ISSUE THREAD

**Issue by theDesuDesu** [SeargeDP/SeargeSDXL#52]
Hello, this is an awesome workflow setup but I am hoping that it would be possible along with existing options to add the new control-loras in this user friendly workflow:
https://huggingface.co/stabilityai/control-lora

(I know this is probably not an easy thing to do and you already have a massive to-do list but I just thought I'd ask)

**Comment by SeargeDP** [comment]
It's planned for a future update

**Comment by theDesuDesu** [comment]
That's awesome! Thanks for the great work!
