### ISSUE TITLE
[Feature Request] - Control-Lora

### ISSUE THREAD

**Issue by ArtaFakhari** [SeargeDP/SeargeSDXL#55]
Hey Guys
Thanks for your good work.
Would you please add support for Control-Lora/ControlNet with SDXL?

**Comment by SeargeDP** [comment]
Check the public test v3.991 on the [releases page](https://github.com/SeargeDP/SeargeSDXL/releases/tag/v3.991)

It needs to be manually installed, during the public test installing with git is not supported. It will be back to installing via git when v4.0 is complete and releases. There are also additional install instructions in the [public test readme file](https://github.com/SeargeDP/SeargeSDXL/blob/dev/README.md).

The v3.991 update adds multi-lora, controlnet, revision, and some other new features.

**Comment by ArtaFakhari** [comment]
Awesome!
