### ISSUE TITLE
Mask Editor image size issue?

### ISSUE THREAD

**Issue by pixitha** [SeargeDP/SeargeSDXL#56]
Pretty sure this is an issue with Mask Editor, not your workflow but wanted to double check.

When I open a image in mask editor, if its a larger image, specifically a tall vertical image (portrait), the bottom of the image is cut off, and also the lower part that isn't cut out, but is near the thickness slider, you can't paint over.

I can't figure out how to resize the mask window, or am I missing something obvious?

**Comment by SeargeDP** [comment]
That's indeed out of my control right now and an issue with the default mask editor in ComfyUI. If drawing a mask manually doesn't work well enough there is always the option to switch to an uploaded mask instead that you can draw with an external tool.

**Comment by SeargeDP** [comment]
This seems to be improved in recent versions of ComfyUI
