### ISSUE TITLE
No Upscaled Preview Image shown in 4.0 HQ workflow

### ISSUE THREAD

**Issue by tinyau** [SeargeDP/SeargeSDXL#59]
![image](https://github.com/SeargeDP/SeargeSDXL/assets/76001/fbb3275e-5d37-47e9-96e0-7862961651d8)

I'm using 4.0 HQ workflow, it is normal that no image shown in "Upscaled Preview Image" even I have set enabled to true?

**Comment by SeargeDP** [comment]
Depends. Did you enable upscaling in the high resolution settings? It's the last setting in that box.

**Comment by tinyau** [comment]
![image](https://github.com/SeargeDP/SeargeSDXL/assets/76001/22a9046d-5b11-454c-a68e-3f12eec5a09a)

This setting? Already set to true.

**Comment by SeargeDP** [comment]
![image](https://github.com/SeargeDP/SeargeSDXL/assets/3330978/a4a1e717-bdd4-4061-8632-247e23581df6)

**Comment by tinyau** [comment]
Oh, my bad. Got it. Thanks a lot.

**Comment by tinyau** [comment]
Oh, my bad. Got it. Thanks a lot.
