### ISSUE TITLE
How to combine img2img with controlnet?

### ISSUE THREAD

**Issue by blx0102** [SeargeDP/SeargeSDXL#6]
I tried to link output condition of controlnet with input base_positive of SeargeSDXLSampler, but got error.
![image](https://github.com/SeargeDP/SeargeSDXL/assets/17761044/de1edda0-7da9-4f15-ac73-53db6295ceb1)

**Comment by blx0102** [comment]
I suddenly realized that controlnet has not supported sdxl yet.

**Comment by SeargeDP** [comment]
I'll close this, you answered your own quesiton :)
