### ISSUE TITLE
Why did I not respond when loading the json file

### ISSUE THREAD

**Issue by leetherO** [SeargeDP/SeargeSDXL#7]
I followed the steps to install and restart the UI, but the interface was empty. The two JSON files in the manual load example would get stuck. Why is it that my comfyui was not installed properly?

**Comment by leetherO** [comment]
I saw searge related nodes in the add note, but not all nodes can be added and some may get stuck. My computer is 4090 and there should be no problem. The comfyui has also been updated. What's the problem

**Comment by SeargeDP** [comment]
Did you try to load one of the example workflows from the json files in the examples folder?
