### ISSUE TITLE
Need an example of inpainting using SeargeSDXLSampler

### ISSUE THREAD

**Issue by wangjia184** [SeargeDP/SeargeSDXL#8]
I tried to load an image with mask, using VAE encoder(for inpainting), and then latent is output to SeargeSDXLSampler

It seems only base model gets the latent.  when I increase the step percentage for refiner model, the image get blurry.

maybe I am doing something wrong.  Can someone provide an example of inpainting using SeargeSDXLSampler

**Comment by SeargeDP** [comment]
Right now inpainting only works with a base ratio of 1.0 which disables the refiner stage. The workflow was only tested for img2img but not for inpainting, so I never noticed that it's not working when the refiner stage is also active. A future workflow is planned with inpainting support, but that's work in progress right now and I don't know how soon it will be available.

**Comment by SeargeDP** [comment]
Inpainting support will be in the next release
