### ISSUE TITLE
Feature request : Implement FreeU (as optional option)

### ISSUE THREAD

**Issue by eonianvr** [SeargeDP/SeargeSDXL#80]
FreeU really brings some neat improvement in some case on the fnal quality. Could you implement this node in your workflow with an option to use it or not?

Impressive work!

**Comment by SeargeDP** [comment]
I'm currently testing a small update that integrates FreeU and plan to release it soon

**Comment by SeargeDP** [comment]
In v4.2 support for FreeU has been added to the workflow.

**Comment by eonianvr** [comment]
thanks Mate!
