### ISSUE TITLE
Unable to load SeargeDP

### ISSUE THREAD

**Issue by west1778** [SeargeDP/SeargeSDXL#84]
Hi, I'm unable to use SeargeDP custom Workflow. Fresh install of everything. The only other custom model is Manager. Installed using .bat file from GitHub https://github.com/SeargeDP/SeargeSDXL. Receiving error message. 

![image](https://github.com/SeargeDP/SeargeSDXL/assets/73608023/ef689a8b-934e-41e4-9ef9-8706e22be90e)

Thank you for your time. Look forward to using your workflow again.

**Comment by SeargeDP** [comment]
The required python dependency is not installed, either follow the steps in the manual install instructions in the readme file or use the install script.

**Comment by west1778** [comment]
> The required Python dependency is not installed, either follow the steps in the manual install instructions in the readme file or use the install script.

I did use the install script as noted in my original post. I reinstalled fresh again and it worked just fine so no idea.
