### ISSUE TITLE
[Feature Request] One Button Prompt

### ISSUE THREAD

**Issue by PsiClone99** [SeargeDP/SeargeSDXL#86]
Since i think version 4 it is impossible to plug One button prompt node instead of the main prompt node input,
Earlier It was working(In version 3.x),  I am attaching a Image using the Older workflow.  You can drop in comfy to check the workflow.

Please bring back the ability to plug the one-button prompt node again !!
![high_res_00038_](https://github.com/SeargeDP/SeargeSDXL/assets/36812989/0dc90352-19b3-42af-8470-644a5b6e6427)

**Comment by PsiClone99** [comment]
Hey, @SeargeDP any Plan to integrate this in the coming future? I saw that the older prompt nodes directly plugged into the Prompt Controller whereas the new one plugs into the prompt adapter. Any way we can make changes to the one-button prompt so that it inputs into the main prompt input of the prompt adapter ?

**Comment by SeargeDP** [comment]
You could right click the prompt input nodes and convert their prompt to input, then feed strings into it. That way the prompt input nodes convert the text to the type that the prompt adapter expects. Does that solve your problem?

**Comment by PsiClone99** [comment]
OMG this worked perfectly, Thank you so much, I was completely unaware of the convert to input function!
