### ISSUE TITLE
FreeU v2...What can feed into this node?

### ISSUE THREAD

**Issue by aegis72** [SeargeDP/SeargeSDXL#87]
It has a "data" input and output, but where does this data come from/go? A different FreeU node, FreeU advanced, inputs and outputs the "model," and I have that working in my setup. I'd prefer the simplicity in your node, but cannot figure how to get it connected. Right now, I have efficent loader XL, I'm using your "unpack sdxl tuple" to get access to the inners of the tuple, then inserting FreeU advanced on the "model" and then zipping it all back up to a tuple again for the Efficient Sampler. 

![image](https://github.com/SeargeDP/SeargeSDXL/assets/118572301/3ffb5722-a8ed-4829-8adc-66e07d86b859)

Any idea?

**Comment by SeargeDP** [comment]
These nodes are UI nodes, they don't do anything on their own. Instead they feed parameters into my workflow.

**Comment by aegis72** [comment]
Ah, I see…used to feed into the larger node after converting some widgets to inputs.thanks.
